### ISSUE TITLE
Require octave

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/octave_kernel-feedstock#17]
Considering as `octave` is provided by `conda-forge` and users would mostly like expect that `conda install octave_kernel` should handle all of its dependencies, it seems reasonable for `octave_kernel` to require `octave` and supply any environment variables or apply patches needed to find the `octave` package.

**Comment by blink1073** [comment]
I disagree.  Octave could be provided by some other installation method, and we don't want to override that version.

**Comment by ocefpaf** [comment]
Octave should be kept as an optional dependency bundle it here is a bad idea.

Next version of `conda` will allow us to do this the right way, no need to force this now.

**Comment by jakirkham** [comment]
I don't follow the rationale. We provide the needed dependencies for the other kernels. An obvious example would be `ipykernel` (though we could debate why that is). However the `spylon-kernel` and `scijava-jupyter-kernel` both pull in the needed dependencies. Why should the `octave_kernel` be any different in this regard?

**Comment by ocefpaf** [comment]
You remove the user choice. Octave installations are quite different and that should be controlled by the user. If you force the `conda-forge` version you make that difficult.

Not to mention that we do not package `octave` for Windows, making this recipe platform specific due to the addition of the selector.

**Comment by blink1073** [comment]
FWIW I tried using the `octave` package from conda-forge on OSX and the kernel picked it up fine.  I suspect the experience would be the same on Linux, since we are looking for the `octave` binary on the `PATH`.

**Comment by jakirkham** [comment]
Well I wasn't able to get it to work with Binder. When I tried my own local Docker container, the issue was it couldn't find the executable. So had to set the environment variable. Guessing it is the same issue on Binder, but I didn't get enough debug information from it to know for sure. Suppose one could create a Dockerfile to get around this issue, but it does feel rather heavy handed. Though perhaps this discussion should be moved somewhere else. Feel free to suggest a location, @blink1073.

**Comment by blink1073** [comment]
https://github.com/Calysto/octave_kernel is a fair place.  I just tried on an Ubuntu 16.04 VM, and the kernel works there as well.
